<?xml version="1.0"?>
<package format="3">
  <name>rasprover_bringup</name>
  <version>0.0.1</version>
  <description>Launch files for the Rasprover ROS 2 node stack.</description>

  <maintainer email="thi.ledinh@gmail.com">jackie167</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rasprover_base</exec_depend>
  <exec_depend>rasprover_control</exec_depend>
  <exec_depend>rasprover_sensors</exec_depend>
  <exec_depend>rasprover_slam</exec_depend>
  <exec_depend>rasprover_ui</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
