<?xml version="1.0"?>
<package format="3">
  <name>rasprover_mux</name>
  <version>0.0.1</version>
  <description>Legacy compatibility wrapper for Rasprover control nodes.</description>

  <maintainer email="thi.ledinh@gmail.com">jackie167</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rasprover_control</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
